||||||||    public function testCreatesByExtractingValueFromRejectedPromise()
    {
        $p = new Promise();
        $e = new \Exception('foo');
        $p->reject($e);
        $p2 = ResponsePromise::fromPromise($p);
        $this->assertInstanceOf('GuzzleHttp\RejectedResponse', $p2);
        try {
            $p2->getStatusCode();
            $this->fail();
        } catch (\Exception $e2) {
            $this->assertSame($e2, $e);
        }
    }

    /**
     * @expectedException \UnexpectedValueException
     */
||||||||||||||||NO_DOC_COMMENTNO_RETURN_TYPE
(
    (AST_ASSIGN
        (AST_VAR)
        (AST_NEW))
    (AST_ASSIGN
        (AST_VAR)
        (AST_NEW
            (
                (SCALAR))))
    (AST_METHOD_CALL
        (AST_VAR)
        (
            (AST_VAR)))
    (AST_ASSIGN
        (AST_VAR)
        (AST_STATIC_CALL
            (
                (AST_VAR))))
    (AST_METHOD_CALL
        (AST_VAR)
        (
            (SCALAR)
            (AST_VAR)))
    (AST_TRY
        (
            (AST_METHOD_CALL
                (AST_VAR))
            (AST_METHOD_CALL
                (AST_VAR)))
        (AST_CATCH_LIST
            (AST_CATCH
                (AST_NAME_LIST)
                (AST_VAR)
                (
                    (AST_METHOD_CALL
                        (AST_VAR)
                        (
                            (AST_VAR)
                            (AST_VAR))))))
        (NULL)))