  public function addTest($callback, $comment = '')
  {
    $this->assertIsCallable($callback);
    $this->testCallbacks[] = $callback;
    $this->testComments[] = $comment;
  }

  /**
   * Adds a callback that is called when an exception is thrown in a test.
   *
   * The callback retrieves the exception as first argument. It
   * should return TRUE if it was able to handle the exception successfully and
   * FALSE otherwise. In the latter case, the exception is thrown globally.
   *
   * @param  callable $callback
   * @throws InvalidArgumentException  If the argument is no callbale
   */
||||||||||||||||HAS_DOC_COMMENTNO_RETURN_TYPE
(NO_PARAM_TYPENO_PARAM_DEFAULTNO_PARAM_TYPENO_PARAM_DEFAULT)
(
    (AST_METHOD_CALL
        (AST_VAR)
        (
            (AST_VAR)))
    (AST_ASSIGN
        (AST_DIM
            (AST_PROP
                (AST_VAR))
            (NULL))
        (AST_VAR))
    (AST_ASSIGN
        (AST_DIM
            (AST_PROP
                (AST_VAR))
            (NULL))
        (AST_VAR)))||||||||